#!/bin/sh
./sondra.sh 10000words.html
./moonlit.sh 10000words.html
./sondra.sh 13ways.html
./moonlit.sh 13ways.html
./sondra.sh 1generation.html
./moonlit.sh 1generation.html
./sondra.sh 1truefriend.html
./moonlit.sh 1truefriend.html
./sondra.sh 2minutes.html
./moonlit.sh 2minutes.html
./sondra.sh 314159.html
./moonlit.sh 314159.html
./sondra.sh 3published.html
./moonlit.sh 3published.html
./sondra.sh 45C1DF3F.html
./moonlit.sh 45C1DF3F.html
./sondra.sh 45C1E206.html
./moonlit.sh 45C1E206.html
./sondra.sh 463B4C0A.html
./moonlit.sh 463B4C0A.html
./sondra.sh 468C4A4E.html
./moonlit.sh 468C4A4E.html
./sondra.sh 468E162B.html
./moonlit.sh 468E162B.html
./sondra.sh 4698FD6E.html
./moonlit.sh 4698FD6E.html
./sondra.sh 46D9F24A.html
./moonlit.sh 46D9F24A.html
./sondra.sh 46DC0D8E.html
./moonlit.sh 46DC0D8E.html
./sondra.sh 46F1BED0.html
./moonlit.sh 46F1BED0.html
./sondra.sh 46FDC2FB.html
./moonlit.sh 46FDC2FB.html
./sondra.sh 471D354F.html
./moonlit.sh 471D354F.html
./sondra.sh 471EA1BB.html
./moonlit.sh 471EA1BB.html
./sondra.sh 4721C022.html
./moonlit.sh 4721C022.html
./sondra.sh 472C5C81.html
./moonlit.sh 472C5C81.html
./sondra.sh 473A528D.html
./moonlit.sh 473A528D.html
./sondra.sh 4757F0E5.html
./moonlit.sh 4757F0E5.html
./sondra.sh 4766EBB1.html
./moonlit.sh 4766EBB1.html
./sondra.sh 4767BC50.html
./moonlit.sh 4767BC50.html
./sondra.sh 476C7887.html
./moonlit.sh 476C7887.html
./sondra.sh 7thday.html
./moonlit.sh 7thday.html
./sondra.sh abmagrising.html
./moonlit.sh abmagrising.html
./sondra.sh acrosstheuniverse.html
./moonlit.sh acrosstheuniverse.html
./sondra.sh afteritfell.html
./moonlit.sh afteritfell.html
./sondra.sh againstblackest.html
./moonlit.sh againstblackest.html
./sondra.sh alackadaynext.html
./moonlit.sh alackadaynext.html
./sondra.sh allliveforever.html
./moonlit.sh allliveforever.html
./sondra.sh alwayson.html
./moonlit.sh alwayson.html
./sondra.sh amanwalksintoabar.html
./moonlit.sh amanwalksintoabar.html
./sondra.sh andmyshadow.html
./moonlit.sh andmyshadow.html
./sondra.sh annuitcoeptis.html
./moonlit.sh annuitcoeptis.html
./sondra.sh aprmay2007link.html
./moonlit.sh aprmay2007link.html
./sondra.sh atminimum.html
./moonlit.sh atminimum.html
./sondra.sh avidtheeye.html
./moonlit.sh avidtheeye.html
./sondra.sh awake0.html
./moonlit.sh awake0.html
./sondra.sh badluckcharm.html
./moonlit.sh badluckcharm.html
./sondra.sh betteroffdead.html
./moonlit.sh betteroffdead.html
./sondra.sh betweenpillarshercules.html
./moonlit.sh betweenpillarshercules.html
./sondra.sh bismuth.html
./moonlit.sh bismuth.html
./sondra.sh blackbasalt.html
./moonlit.sh blackbasalt.html
./sondra.sh blue2007.html
./moonlit.sh blue2007.html
./sondra.sh blueplace.html
./moonlit.sh blueplace.html
./sondra.sh bluescreen.html
./moonlit.sh bluescreen.html
./sondra.sh blueshifts.html
./moonlit.sh blueshifts.html
./sondra.sh bluetarp.html
./moonlit.sh bluetarp.html
./sondra.sh brainworm.html
./moonlit.sh brainworm.html
./sondra.sh brightwings.html
./moonlit.sh brightwings.html
./sondra.sh buggy.html
./moonlit.sh buggy.html
./sondra.sh bywayofjustification.html
./moonlit.sh bywayofjustification.html
./sondra.sh canthelpfalling.html
./moonlit.sh canthelpfalling.html
./sondra.sh cbr.html
./moonlit.sh cbr.html
./sondra.sh chariot.html
./moonlit.sh chariot.html
./sondra.sh chill.html
./moonlit.sh chill.html
./sondra.sh choiceschoices.html
./moonlit.sh choiceschoices.html
./sondra.sh cigarswerenotcigars.html
./moonlit.sh cigarswerenotcigars.html
./sondra.sh cinqlone.html
./moonlit.sh cinqlone.html
./sondra.sh commando.html
./moonlit.sh commando.html
./sondra.sh compromised.html
./moonlit.sh compromised.html
./sondra.sh contrail.html
./moonlit.sh contrail.html
./sondra.sh coreofdarkness.html
./moonlit.sh coreofdarkness.html
./sondra.sh cumshaw.html
./moonlit.sh cumshaw.html
./sondra.sh darkhalo.html
./moonlit.sh darkhalo.html
./sondra.sh day1236.html
./moonlit.sh day1236.html
./sondra.sh dec2006link.html
./moonlit.sh dec2006link.html
./sondra.sh dentata.html
./moonlit.sh dentata.html
./sondra.sh derorden.html
./moonlit.sh derorden.html
./sondra.sh destroyallmonsters.html
./moonlit.sh destroyallmonsters.html
./sondra.sh diplomaticprotocol.html
./moonlit.sh diplomaticprotocol.html
./sondra.sh dn77.html
./moonlit.sh dn77.html
./sondra.sh donotadjust.html
./moonlit.sh donotadjust.html
./sondra.sh doyouseewhatisee.html
./moonlit.sh doyouseewhatisee.html
./sondra.sh drinkinggame.html
./moonlit.sh drinkinggame.html
./sondra.sh ducttape.html
./moonlit.sh ducttape.html
./sondra.sh dustgully.html
./moonlit.sh dustgully.html
./sondra.sh dysfunction.html
./moonlit.sh dysfunction.html
./sondra.sh earcandy.html
./moonlit.sh earcandy.html
./sondra.sh enemiesenemy.html
./moonlit.sh enemiesenemy.html
./sondra.sh escort.html
./moonlit.sh escort.html
./sondra.sh exhibitj.html
./moonlit.sh exhibitj.html
./sondra.sh extendedleave.html
./moonlit.sh extendedleave.html
./sondra.sh f68.html
./moonlit.sh f68.html
./sondra.sh failuretothrive.html
./moonlit.sh failuretothrive.html
./sondra.sh fever.html
./moonlit.sh fever.html
./sondra.sh finefinelines.html
./moonlit.sh finefinelines.html
./sondra.sh fleshflesh.html
./moonlit.sh fleshflesh.html
./sondra.sh foaf.html
./moonlit.sh foaf.html
./sondra.sh foofriends.html
./moonlit.sh foofriends.html
./sondra.sh fromtheeast.html
./moonlit.sh fromtheeast.html
./sondra.sh gateward.html
./moonlit.sh gateward.html
./sondra.sh gcd.html
./moonlit.sh gcd.html
./sondra.sh geophage.html
./moonlit.sh geophage.html
./sondra.sh getoverit.html
./moonlit.sh getoverit.html
./sondra.sh gettingugly.html
./moonlit.sh gettingugly.html
./sondra.sh gliese581c.html
./moonlit.sh gliese581c.html
./sondra.sh godsmack.html
./moonlit.sh godsmack.html
./sondra.sh gonebetter.html
./moonlit.sh gonebetter.html
./sondra.sh goodspacewalkspoiled.html
./moonlit.sh goodspacewalkspoiled.html
./sondra.sh grackle.html
./moonlit.sh grackle.html
./sondra.sh gravjunkies.html
./moonlit.sh gravjunkies.html
./sondra.sh greeneyedmonster.html
./moonlit.sh greeneyedmonster.html
./sondra.sh heavenstobetsy.html
./moonlit.sh heavenstobetsy.html
./sondra.sh homefront.html
./moonlit.sh homefront.html
./sondra.sh horizonhorizon.html
./moonlit.sh horizonhorizon.html
./sondra.sh hum.html
./moonlit.sh hum.html
./sondra.sh humanvector.html
./moonlit.sh humanvector.html
./sondra.sh hygiene.html
./moonlit.sh hygiene.html
./sondra.sh imnotone.html
./moonlit.sh imnotone.html
./sondra.sh indelible.html
./moonlit.sh indelible.html
./sondra.sh indexentry.html
./moonlit.sh indexentry.html
./sondra.sh infall.html
./moonlit.sh infall.html
./sondra.sh inreview.html
./moonlit.sh inreview.html
./sondra.sh inthemidst.html
./moonlit.sh inthemidst.html
./sondra.sh intimateapparel.html
./moonlit.sh intimateapparel.html
./sondra.sh isdm.html
./moonlit.sh isdm.html
./sondra.sh itcameonemorning.html
./moonlit.sh itcameonemorning.html
./sondra.sh jan07link.html
./moonlit.sh jan07link.html
./sondra.sh jerseyshore.html
./moonlit.sh jerseyshore.html
./sondra.sh julia.html
./moonlit.sh julia.html
./sondra.sh julianday2454269.html
./moonlit.sh julianday2454269.html
./sondra.sh lakesidetitan.html
./moonlit.sh lakesidetitan.html
./sondra.sh laststronghold.html
./moonlit.sh laststronghold.html
./sondra.sh lilgreendot.html
./moonlit.sh lilgreendot.html
./sondra.sh livery.html
./moonlit.sh livery.html
./sondra.sh longdelayedfurlough.html
./moonlit.sh longdelayedfurlough.html
./sondra.sh loophole.html
./moonlit.sh loophole.html
./sondra.sh loveshack.html
./moonlit.sh loveshack.html
./sondra.sh madisonia.html
./moonlit.sh madisonia.html
./sondra.sh maincourse.html
./moonlit.sh maincourse.html
./sondra.sh mantissaconsciousness.html
./moonlit.sh mantissaconsciousness.html
./sondra.sh mar2007link.html
./moonlit.sh mar2007link.html
./sondra.sh maystar.html
./moonlit.sh maystar.html
./sondra.sh metadoxy.html
./moonlit.sh metadoxy.html
./sondra.sh microscopy.html
./moonlit.sh microscopy.html
./sondra.sh middleschool.html
./moonlit.sh middleschool.html
./sondra.sh mirroruniversenear.html
./moonlit.sh mirroruniversenear.html
./sondra.sh misdirected.html
./moonlit.sh misdirected.html
./sondra.sh misfire.html
./moonlit.sh misfire.html
./sondra.sh model.html
./moonlit.sh model.html
./sondra.sh model.html.bak
./moonlit.sh model.html.bak
./sondra.sh movingover.html
./moonlit.sh movingover.html
./sondra.sh mrmojorisin.html
./moonlit.sh mrmojorisin.html
./sondra.sh myeyes.html
./moonlit.sh myeyes.html
./sondra.sh neckdown.html
./moonlit.sh neckdown.html
./sondra.sh neogamist.html
./moonlit.sh neogamist.html
./sondra.sh newadam.html
./moonlit.sh newadam.html
./sondra.sh nonconformingusage.html
./moonlit.sh nonconformingusage.html
./sondra.sh notlikeoneofus.html
./moonlit.sh notlikeoneofus.html
./sondra.sh nowwhat.html
./moonlit.sh nowwhat.html
./sondra.sh olbagobolts.html
./moonlit.sh olbagobolts.html
./sondra.sh oldengolden.html
./moonlit.sh oldengolden.html
./sondra.sh omegapoint.html
./moonlit.sh omegapoint.html
./sondra.sh oncethoughtextinct.html
./moonlit.sh oncethoughtextinct.html
./sondra.sh ourlittleritual.html
./moonlit.sh ourlittleritual.html
./sondra.sh ourtrust.html
./moonlit.sh ourtrust.html
./sondra.sh pageofmyown.html
./moonlit.sh pageofmyown.html
./sondra.sh passiveaggressive.html
./moonlit.sh passiveaggressive.html
./sondra.sh pco.html
./moonlit.sh pco.html
./sondra.sh permanentcollection.html
./moonlit.sh permanentcollection.html
./sondra.sh phoningitin.html
./moonlit.sh phoningitin.html
./sondra.sh picketduty.html
./moonlit.sh picketduty.html
./sondra.sh pickup411.html
./moonlit.sh pickup411.html
./sondra.sh placestillspinning.html
./moonlit.sh placestillspinning.html
./sondra.sh poetrybad.html
./moonlit.sh poetrybad.html
./sondra.sh postholocene.html
./moonlit.sh postholocene.html
./sondra.sh priestlygift.html
./moonlit.sh priestlygift.html
./sondra.sh pulvusextremis.html
./moonlit.sh pulvusextremis.html
./sondra.sh queenbeeslunchtable.html
./moonlit.sh queenbeeslunchtable.html
./sondra.sh railroadout.html
./moonlit.sh railroadout.html
./sondra.sh randomdomain2006.html
./moonlit.sh randomdomain2006.html
./sondra.sh rarity.html
./moonlit.sh rarity.html
./sondra.sh recolorado.html
./moonlit.sh recolorado.html
./sondra.sh redsailsinthesunset.html
./moonlit.sh redsailsinthesunset.html
./sondra.sh reincarnationatadistance.html
./moonlit.sh reincarnationatadistance.html
./sondra.sh relativism.html
./moonlit.sh relativism.html
./sondra.sh repetition.html
./moonlit.sh repetition.html
./sondra.sh revengeofthenerds.html
./moonlit.sh revengeofthenerds.html
./sondra.sh reverence.html
./moonlit.sh reverence.html
./sondra.sh roadhypnosis.html
./moonlit.sh roadhypnosis.html
./sondra.sh rocketmensch.html
./moonlit.sh rocketmensch.html
./sondra.sh rodentcollector.html
./moonlit.sh rodentcollector.html
./sondra.sh roombarita.html
./moonlit.sh roombarita.html
./sondra.sh rot20+6.html
./moonlit.sh rot20+6.html
./sondra.sh roundaphelion.html
./moonlit.sh roundaphelion.html
./sondra.sh sanctuarynereus.html
./moonlit.sh sanctuarynereus.html
./sondra.sh saturdaynight.html
./moonlit.sh saturdaynight.html
./sondra.sh savannahdrome.html
./moonlit.sh savannahdrome.html
./sondra.sh sawthat.html
./moonlit.sh sawthat.html
./sondra.sh scenesleepingcity.html
./moonlit.sh scenesleepingcity.html
./sondra.sh scifaikuest0207.html
./moonlit.sh scifaikuest0207.html
./sondra.sh scoutcamp.html
./moonlit.sh scoutcamp.html
./sondra.sh searchwait.html
./moonlit.sh searchwait.html
./sondra.sh semihemidemiquaver.html
./moonlit.sh semihemidemiquaver.html
./sondra.sh sensorydeprivation.html
./moonlit.sh sensorydeprivation.html
./sondra.sh shantytown4.html
./moonlit.sh shantytown4.html
./sondra.sh shippingreceiving.html
./moonlit.sh shippingreceiving.html
./sondra.sh sketch0107.html
./moonlit.sh sketch0107.html
./sondra.sh sketchbook0207.html
./moonlit.sh sketchbook0207.html
./sondra.sh sobriquet.html
./moonlit.sh sobriquet.html
./sondra.sh somepeace.html
./moonlit.sh somepeace.html
./sondra.sh songofthefatlady.html
./moonlit.sh songofthefatlady.html
./sondra.sh sonnetsdragaeran.html
./moonlit.sh sonnetsdragaeran.html
./sondra.sh sortoftherapy.html
./moonlit.sh sortoftherapy.html
./sondra.sh spiraleenthefair.html
./moonlit.sh spiraleenthefair.html
./sondra.sh sr0.html
./moonlit.sh sr0.html
./sondra.sh sr1.html
./moonlit.sh sr1.html
./sondra.sh staghorndell.html
./moonlit.sh staghorndell.html
./sondra.sh starsong.html
./moonlit.sh starsong.html
./sondra.sh statement.html
./moonlit.sh statement.html
./sondra.sh stepone.html
./moonlit.sh stepone.html
./sondra.sh stillamystery.html
./moonlit.sh stillamystery.html
./sondra.sh stilltheyburn.html
./moonlit.sh stilltheyburn.html
./sondra.sh symbiote.html
./moonlit.sh symbiote.html
./sondra.sh takingplanet3.html
./moonlit.sh takingplanet3.html
./sondra.sh test0.html
./moonlit.sh test0.html
./sondra.sh testostimony.html
./moonlit.sh testostimony.html
./sondra.sh thebaneofepsilon.html
./moonlit.sh thebaneofepsilon.html
./sondra.sh thepale.html
./moonlit.sh thepale.html
./sondra.sh thepressure.html
./moonlit.sh thepressure.html
./sondra.sh theyhadnodefense.html
./moonlit.sh theyhadnodefense.html
./sondra.sh theyhungup.html
./moonlit.sh theyhungup.html
./sondra.sh thislovesong.html
./moonlit.sh thislovesong.html
./sondra.sh thumbelinadestroyer.html
./moonlit.sh thumbelinadestroyer.html
./sondra.sh timeofstrife.html
./moonlit.sh timeofstrife.html
./sondra.sh toomanypoems.html
./moonlit.sh toomanypoems.html
./sondra.sh top2006ku.html
./moonlit.sh top2006ku.html
./sondra.sh tovastydeeps.html
./moonlit.sh tovastydeeps.html
./sondra.sh trackyourorder.html
./moonlit.sh trackyourorder.html
./sondra.sh traildiary.html
./moonlit.sh traildiary.html
./sondra.sh tunguska.html
./moonlit.sh tunguska.html
./sondra.sh unappreciated.html
./moonlit.sh unappreciated.html
./sondra.sh unionavatars.html
./moonlit.sh unionavatars.html
./sondra.sh unlimitedlos.html
./moonlit.sh unlimitedlos.html
./sondra.sh vessel.html
./moonlit.sh vessel.html
./sondra.sh vicesquad.html
./moonlit.sh vicesquad.html
./sondra.sh viptour.html
./moonlit.sh viptour.html
./sondra.sh vspikes.html
./moonlit.sh vspikes.html
./sondra.sh waft.html
./moonlit.sh waft.html
./sondra.sh weekendgetaway.html
./moonlit.sh weekendgetaway.html
./sondra.sh wehavenow.html
./moonlit.sh wehavenow.html
./sondra.sh whatyouthink.html
./moonlit.sh whatyouthink.html
./sondra.sh whencoldwindsblew.html
./moonlit.sh whencoldwindsblew.html
./sondra.sh which.html
./moonlit.sh which.html
./sondra.sh whosbeeneating.html
./moonlit.sh whosbeeneating.html
./sondra.sh widerthanthesky.html
./moonlit.sh widerthanthesky.html
./sondra.sh winewomensong.html
./moonlit.sh winewomensong.html
./sondra.sh withoneseyes.html
./moonlit.sh withoneseyes.html
./sondra.sh worththeprice.html
./moonlit.sh worththeprice.html
./sondra.sh wreathofflame.html
./moonlit.sh wreathofflame.html
./sondra.sh wwe.html
./moonlit.sh wwe.html
./sondra.sh yaais.html
./moonlit.sh yaais.html
./sondra.sh yapas.html
./moonlit.sh yapas.html
./sondra.sh zillionwithaz.html
./moonlit.sh zillionwithaz.html
